title: <p align="center"> Venkatesh Beeraka </p>
logo: /assets/img/venbee.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/venkatesh-beeraka">LinkedIn</a> |
  <a href="https://github.com/venbee">GitHub</a>
  
  <br>   
  I am working as an Azure DevOps engineer in an MNC with 2+ ears Experience.
  I have good knowledge on DevOps concepts such as CI/CD Pipelines, containerization, 
  version control, cloud computing, database management, load balancing etc.
  <br>
  </p>
theme: jekyll-theme-minimal
